# typed: false
# frozen_string_literal: true

# This file was generated by running `brew tap curogom/curo-prompt` and then `brew create curo-prompt`
class CuroPrompt < Formula
  desc "CLI tool for analyzing, evaluating, and optimizing LLM prompts"
  homepage "https://github.com/curogom/curo-prompt"
  url "https://github.com/curogom/curo-prompt/archive/refs/tags/v0.1.3.tar.gz"
  sha256 "cb3a8e4649f2b589df531f8c76aed9278fa12f72ed44d5d650fe439ca0775dba"
  license "Apache-2.0"
  version "0.1.3"
  head "https://github.com/curogom/curo-prompt.git", branch: "main"

  depends_on "go" => :build

  def install
    # Build the binary with version info
    version_str = version.to_s
    build_time = Time.now.utc.strftime("%Y-%m-%d_%H:%M:%S")
    
    # Build ldflags as a single quoted string for -ldflags flag
    # Important: All flags must be in one string passed to -ldflags
    ldflags = [
      "-s",
      "-w",
      "-X main.Version=#{version_str}",
      "-X main.BuildTime=#{build_time}",
      "-X main.GitCommit=#{version_str}"
    ].join(" ")
    
    # Use shell command to ensure ldflags is passed as single quoted string
    # Ruby's system with array splits ldflags by spaces, causing issues
    system("go build -ldflags '#{ldflags}' -o #{bin}/curo-prompt ./cmd/curo-prompt")
  end

  test do
    # Test basic functionality
    system "#{bin}/curo-prompt", "--version"
  end
end
